SELECT stream.*
from "PCRCallRecordStreams" stream
    join "PCRCallRecordDetails" details on details."Id" = stream."CallId"
where stream."Label" = 'main-audio'
    and details."CallType" = 'PeerToPeer'
    and CAST(stream."StartDateTime" as TIMESTAMP) >= cast('2023-09-10' as TIMESTAMP)
ORDER by "CallId",
    "MediaId"
limit 100;
select *
from "PCRCallRecordNetworks" network
where "MediaId" = '1df7b94f-7489-4434-896a-b70f7279aee9'
ORDER By "MediaId"
limit 10;
"Id" "9f6cfaaf-f0fb-4ce9-ab88-5bb980396c11" -- SELECT DISTINCT("Label") from "PCRCallRecordStreams" stream;
-- "main-video1"
-- "main-video43"
-- "main-video33"
-- "applicationsharing-video"
-- "main-video18"
-- "main-video37"
-- "main-video8"
-- "main-video10"
-- "main-video9"
-- "main-video38"
-- "main-video3"
-- "main-video35"
-- "main-video25"
-- "main-video12"
-- "main-video21"
-- "main-video4"
-- "main-video17"
-- "main-video5"
-- "main-video19"
-- "main-video42"
-- "main-video"
-- "data"
-- "main-video47"
-- "main-video34"
-- "main-video-vtc"
-- "main-video32"
-- "main-video15"
-- "main-video39"
-- "main-video23"
-- "main-video29"
-- "main-video41"
-- "main-video30"
-- "main-video13"
-- "main-video27"
-- "main-video6"
-- "main-video49"
-- "main-audio"
-- "main-video31"
-- "main-audio-vtc"
-- "main-video14"
-- "main-video36"
-- "applicationsharing-video-vtc"
-- "main-video48"
-- "main-video26"
-- "main-video24"
-- "main-video16"
-- "main-video44"
-- "main-video20"
-- "main-video11"
-- "main-video46"
-- "main-video22"
-- "main-video28"
-- "main-video40"
-- "main-video2"
-- "main-video45"
-- "main-video7"